apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: petri_prometheus
    url: {{ .URL }}
    isDefault: true
    jsonData:
      prometheusType: "Prometheus"
    version: 1
    editable: false
