# Configuration file version
apiVersion: 1

# List of data sources to delete from the database.
deleteDatasources:
  - name: Graphite
    orgId: 1

# List of data sources to insert/update depending on what's
# available in the database.
datasources:
  # <string, required> Sets the name you use to refer to
  # the data source in panels and queries.
  - name: Graphite
    type: prometheus
    access: proxy
    orgId: 1
    uid: petri_prometheus
    url: {{ .URL }}
    isDefault: true
    jsonData:
      prometheusType: "Prometheus"
    version: 1
    editable: false