name: "Run tests"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
    types:
      - opened
      - edited
      - synchronize

jobs:
  unit-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - name: Run unit tests
        run: |
          make tidy
          make unit-test
